version: "3.9"
services:

  zookeeper-1:
    container_name: zookeeper-1
    image: confluentinc/cp-zookeeper:latest
    build:
      context: ./zookeeper
    volumes:
      - type: bind
        source: ./config/zookeeper-1/zookeeper.properties
        target: /kafka/config/zookeeper.properties
      - type: bind
        source: ./data/zookeeper-1
        target: /tmp/zookeeper
    networks:
    - kafka

  kafka-1:
    container_name: kafka-1
    image: confluentinc/cp-kafka:latest
    build: 
      context: .
    volumes:
      - type: bind
        source: ./config/kafka-1/server.properties
        target: /kafka/config/server.properties
      - type: bind
        source: ./data/kafka-1
        target: /tmp/kafka-logs
    networks:
    - kafka

  kafka-2:
    container_name: kafka-2
    image: confluentinc/cp-kafka:latest
    build: 
      context: .
    volumes:
      - type: bind
        source: ./config/kafka-2/server.properties
        target: /kafka/config/server.properties
      - type: bind
        source: ./data/kafka-2
        target: /tmp/kafka-logs
    networks:
    - kafka

  kafka-3:
    container_name: kafka-3
    image: confluentinc/cp-kafka:latest
    build: 
      context: .
    volumes:
      - type: bind
        source: ./config/kafka-3/server.properties
        target: /kafka/config/server.properties
      - type: bind
        source: ./data/kafka-3
        target: /tmp/kafka-logs
    networks:
    - kafka

  kafka-producer:
    container_name: kafka-producer
    image: confluentinc/cp-kafka:latest
    build: 
      context: .
    working_dir: /kafka
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    networks:
    - kafka

  kafka-consumer:
    container_name: kafka-consumer
    image: confluentinc/cp-kafka:latest
    build: 
      context: .
    working_dir: /kafka
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    networks:
    - kafka

  # kafka-consumer-go:
  #   container_name: kafka-consumer-go
  #   image: aimvector/kafka-consumer-go:1.0.0
  #   build: 
  #     context: ./applications/consumer
  #   environment:
  #   - "KAFKA_PEERS=kafka-1:9092,kafka-2:9092,kafka-3:9092"
  #   - "KAFKA_TOPIC=Orders"
  #   - "KAFKA_VERSION=2.7.0"
  #   - "KAFKA_GROUP=orders"
  #   networks:
  #   - kafka
    
networks: 
  kafka:
    name: kafka

volumes:
  data: