apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: cs3219
spec:
  # type: ClusterIP
  type: NodePort
  selector:
    app: order-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30608
    